Feature: SignUp Feature 

    Feature Description

    Scenario: Sign Up with a new user

    Given I open a main page
    When I clicked a "Sign up" button on the Main Page
    And I type autogenerated value in the "username" field
    And I type autogenerated value in the "password" field
    And I submit by clicking the sign up button
    Then I validate that alert message contains "Sign up successful" and submit