const { Given, When, Then } = require('@cucumber/cucumber');
const utils = require('../../lib/utils');
const signUpWindow = require('../../support/windows/signUpWindow');
const expect = require('chai').expect;

let randomUsername;
let randomPassword;

When(
	'I type autogenerated value in the {string} field',
	async function (textField) {
		switch (textField) {
			case 'username':
				randomUsername = await utils.generateRandomString(8);
				await utils.clickAndTypeText(
					this.page,
					signUpWindow.textFields.username,
					randomUsername
				);
				break;
			case 'password':
				randomPassword = await utils.generateRandomString(8);
				await utils.clickAndTypeText(
					this.page,
					signUpWindow.textFields.password,
					randomPassword
				);
                await this.page.waitForTimeout(1000);
				break;
		}
	}
);

When('I submit by clicking the sign up button', async function () {
	await utils.clickByXpath(this.page, signUpWindow.buttons.signUp);
});

Then('I validate that alert message contains {string} and submit', async function(message){
    await utils.checkAndAcceptAlertMessage(this.page, message);
    //await this.page.waitForTimeout(2000);
})

/***
 * 

    And I submit by clicking the sign up button
 */
